Sprk 269
ADA-research/Sparkle pull request #18
Opened 2024-05-29 12:51 UTC by thijssnelleman

Major refactor of parallel portfolio.

2024-06-06 09:17 UTC, jeroenrook requested changes

2024-06-06 09:18 UTC, thijssnelleman commented on sparkle/platform/settings_help.py
> +    DEFAULT_parallel_portfolio_check_interval = 4
Value as found in the original parallel portfolio implementation

2024-06-10 08:09 UTC, thijssnelleman commented on sparkle/solver/solver.py
> +    def build_solver_cmd(self: Solver, instance: str, configuration: dict = {},
This is a very good point. This happens in many locations of Sparkle and should be checked

2024-06-11 12:56 UTC, thijssnelleman commented on CLI/run_parallel_portfolio.py
> +                               "seed": 1,
This has now been fixed: The user can specify in the settings how many random seeds must be made for each solver, and can run multiple solvers at the same time in one portfolio.

2024-06-19 12:31 UTC, jeroenrook commented
Running the example `parallel_portfolio_runtime.sh` shows an PAR10 score of the portfolio of 4817.01, which cannot be possible with a cutoff time of 60 seconds.

2024-06-19 12:38 UTC, jeroenrook commented
What is the purpose of cancelled and best solver for the portfolio table in the report? Als tables are missing captions and are not centred.

2024-06-19 12:47 UTC, jeroenrook requested changes
The reporting of the portfolio seems to not work as desired. See comments above. For a portfolio I expect to see the solving time (by running solvers in parallel) and the CPU time. For example, Solver A takes 5 seconds to solve and Solver B is cancelled after 5 seconds, then the solving time would be 5 seconds, but the CPU time 10.

2024-06-19 13:07 UTC, jeroenrook commented
Report is also written to Output/Selection, which should be changed to ParallelPortfolio

2024-06-20 08:12 UTC, merged