Sprk 220
ADA-research/Sparkle pull request #9
Opened 2024-05-09 16:54 UTC by hadarshavit

Add a CLI option to set autofolio's  timeout and set it by default to 48h (as suggested by Lindauer et al 2015)

2024-05-10 07:43 UTC, thijssnelleman commented
When running the selection example in Sparkle, does that mean it will now take 48h?

2024-05-10 08:29 UTC, hadarshavit commented
Yes, we can set it using the new CLI argument to 60 seconds.
In general it is necessary to run AutoFolio for at least a few hours.
In the future we can parallelise it so it will take less time.

2024-05-10 09:51 UTC, thijssnelleman commented
> Yes, we can set it using the new CLI argument to 60 seconds. In general it is necessary to run AutoFolio for at least a few hours. In the future we can parallelise it so it will take less time.

That sounds really good.  The 48 hours is far too long as a default value. This should be added as a setting in the sparkle_settings and by default I think a value of 60 seconds is good. Whenever this value is used as a variable, you can use the 48h setting and explain this number with the paper reference in the docstring.

2024-05-10 09:54 UTC, thijssnelleman requested changes
Needs some changes to explain the ``suggested settings'' from Lindauer et al. (2015) and something that doesn't confuse the user by default (Waiting 48h is unreasonable for an inexperienced user)

2024-05-10 09:54 UTC, thijssnelleman commented on CLI/support/compute_marginal_contribution_help.py
> +        selector_timeout=172000) -> list[tuple[str, float]]:
Docstring update with paper reference explaining this value

2024-05-10 09:54 UTC, thijssnelleman commented on CLI/support/construct_portfolio_selector_help.py
> +                                         selector_timeout=172000) -> bool:
Docstring explaining the value

2024-05-10 09:54 UTC, thijssnelleman commented on sparkle/platform/settings_help.py
> +    DEFAULT_portfolio_construction_timeout = 172000
Set default value to 60s

2024-05-10 09:54 UTC, thijssnelleman commented on sparkle/platform/settings_help.py
> +
Also needs a setting parse so user can change this default value from the sparkle_settings.ini

2024-05-10 09:54 UTC, thijssnelleman commented on tests/test_marginal_contribution_help.py
> +            selector_timeout=60
Nice

2024-05-31 11:19 UTC, thijssnelleman approved these changes

2024-05-31 11:46 UTC, merged